language: go
dist: bionic
go:
  - 1.13.x
os:
  - linux
  - osx

before_script:
  - make download

script:
  - go build ./cmd/moleculec-es
  - make test
  - make fmt
  - git diff --exit-code

jobs:
  include:
    - stage: deploy
      provider: script
      script: curl -sL https://git.io/goreleaser | bash
      os: linux
      go: 1.13.x
      on:
        tags: true
